[package]
publish = false
name = "stedy"
version = "1.0.0-rc.1"
edition = "2021"

description = "Easy-to-use primitives for modern cryptographic tools and protocols"
keywords = [
    "cryptography",
    "primitives",
    "encryption",
    "signatures",
    "hashing"
]
repository = "https://github.com/christoffercarlsson/stedy"

authors = ["Christoffer Carlsson <cc@christoffercarlsson.com>"]
license = "MIT"

[lib]
name = "stedy"

[[bench]]
name = "stedy"
harness = false

[dependencies]
getrandom = { version = "0.3.4", default-features = false, optional = true }

[dev-dependencies]
criterion = "0.8.1"

[features]
default = []
ffi = ["getrandom"]
getrandom = ["dep:getrandom"]
hazmat = []
shamir = []
