[package]
name = "stedy"
version = "1.0.0-beta.5"
edition = "2021"
publish = false

description = "A solid foundation for modern cryptographic tools and protocols"
repository = "https://github.com/christoffercarlsson/stedy"
keywords = ["cryptography", "encryption", "hashing", "primitives", "signatures"]

authors = ["Christoffer Carlsson <cc@christoffercarlsson.com>"]
license = "MIT"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
features = ["docs"]

[lib]
name = "stedy"

[[bench]]
harness = false
name = "stedy"
path = "benchmarks/main.rs"

[dependencies]
getrandom = { version = "0.4.3", default-features = false, optional = true }

[dev-dependencies]
criterion = "0.8.2"

[features]
default = []
docs = ["getrandom", "hazmat", "secret_sharing"]
getrandom = ["dep:getrandom"]
hazmat = []
secret_sharing = []

[profile.release]
opt-level = 3
debug = false
strip = true
debug-assertions = false
overflow-checks = false
lto = true

[profile.ffi]
inherits = "release"
panic = "abort"
codegen-units = 1
