export const FORMAT_MESSAGE_DELETE = 'Delete `{{ deleteText }}`'
export const FORMAT_MESSAGE_INSERT = 'Insert `{{ insertText }}`'
export const FORMAT_MESSAGE_REPLACE =
  'Replace `{{ deleteText }}` with `{{ insertText }}`'
export const FORMAT_RULE = 'stedy/format'
export const LANGUAGE_CSS = 'css'
export const LANGUAGE_HTML = 'html'
export const LANGUAGE_JAVASCRIPT = 'javascript'
export const LANGUAGE_JSON = 'json'
export const LANGUAGE_MARKDOWN = 'markdown'
export const LANGUAGE_TYPESCRIPT = 'typescript'
export const PARSER_CSS = 'css'
export const PARSER_HTML = 'html'
export const PARSER_JAVASCRIPT = 'babel'
export const PARSER_JSON = 'json-stringify'
export const PARSER_MARKDOWN = 'markdown'
export const PARSER_TYPESCRIPT = 'babel-ts'
